backend:
  name: github
  repo: matt-d-webb/blog

media_folder: "static/uploads"
public_folder: "uploads"

collections:
  - name: "blog"
    label: "Posts"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: image, label: Image, widget: image }
      - { name: date, label: Date, widget: date }
      - { name: tag, label: Tag, widget: text }

